version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: server
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data:
