# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pg'
gem 'puma'
gem 'rake'
gem 'sequel'
gem 'sidekiq'
gem 'sinatra'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false
end
